현재 개선해야 하는 부분
selab-hs/selab-lotto-simulator pull request #1
Opened 2022-07-31 16:18 UTC by InJun2

- switch 를 이용한 로직 비교 -> 이걸 어떤 방식으로 바꿀 수 있는지 고민
- if 문을 interface 로 변경하는 방법 고민
- compareRepeatedResult 에 로직이 너무 김 -> 줄이기 목표

2022-08-02 04:49 UTC, DongGeon0908 requested changes
굳굳입니다!!
아래 내용을 참고해서 수정해보시면 좋을 것 같아요!

1. 역할과 책임을 생각하며 메서드 쪼개기!
2. enum 활용하기!
3. stream 써보기!

2022-08-02 04:49 UTC, DongGeon0908 commented on src/main/java/view/OutputScreen.java
> +        System.out.println("*******************************");
너무 많은 로직이 메서드에 있네요
for문 2번쓰는건 지양해주세요!

2022-08-02 04:49 UTC, DongGeon0908 commented on src/main/java/run/ComparisonNumbers.java
> +    }
enum으로 구현해보시죠!

2022-08-02 04:49 UTC, DongGeon0908 commented on src/main/java/run/ComparisonNumbers.java
> +    }
메서드가 길어진다면, 해당 메서드가 너무 많은 역할과 책임을 갖고 있다는 것을 증명하는 것입니다!!
조금 더 쪼개보시죵

2022-08-02 04:49 UTC, DongGeon0908 commented on src/main/java/run/ComparisonNumbers.java
> +    }
생성자를 이용하는 건 굳굳

2022-08-02 04:49 UTC, DongGeon0908 commented on src/main/java/model/SimulatedLottoNumber.java
> +    private Set<Integer> generateSimulationNumbers() {
stream을 써보는 건 어떨까요?

2022-08-06 13:09 UTC, DongGeon0908 requested changes
좋은 것 같아요!!
이번에 목표는 테스트 코드입니다!!

다음 리뷰 요청에서는 테스트 코드를 작성해주셔서 리뷰 요청 부탁드립니다.
(추가적으로 코드를 조금 더 예쁘게?? 작성하는 연습도!!)

2022-08-06 13:09 UTC, DongGeon0908 commented on src/test/java/ExampleTest.java
>  public class ExampleTest {
이번 기회에 테스트 코드를 작성하시는 건 어떨까요?

2022-08-06 13:09 UTC, DongGeon0908 commented on src/main/java/view/OutputScreen.java
> +public class OutputScreen {
```suggestion
public class OutputView {
```

2022-08-06 13:09 UTC, DongGeon0908 commented on src/main/java/view/OutputScreen.java
> +        AtomicInteger counter = new AtomicInteger(0);
AtomicInteger 요것이 무엇일까요?

2022-08-06 13:09 UTC, DongGeon0908 commented on src/main/java/run/ComparisonNumbers.java
> +    }
stream으로 돌리는 것도 좋을 것 같네요

2022-08-12 05:34 UTC, InJun2 commented on src/main/java/view/OutputScreen.java
> +        AtomicInteger counter = new AtomicInteger(0);
int i를 지역변수로 사용한 후 람다식 반환값에 i++; 를 사용했더니 오류가 발생했고 자동 해결을 통해 AtomicInteger로 변환되었음.
해당 클래스가 무엇인지 모르고 사용했는데 이후 찾아보니 주로 동기화를 위해 사용한다고 함
멀티스레드 환경에서 동시성 관리를 위해 도입된 자료형으로 스트림을 순회하면서 외부 변수에 접근하려고 하면 동시성 관리를 위해 Atomic 자료형을 사용해야한다고 함

2022-08-14 05:31 UTC, DongGeon0908 reviewed
고생했어요
별도로 리뷰드릴 내용은 없을 것 같네요
현재 코드를 검증할 수 있는 테스트 코드를 작성해주세요

2023-07-15 17:55 UTC, merged