Harim/working
selab-hs/selab-lotto-simulator pull request #2
Opened 2022-09-14 09:58 UTC by HwangHarim

1. MVC 적용
2. 일급컬랙션 적용
3. 역할 분담에 생각해보고 분리

리뷰 감사합니다!

2022-09-14 12:45 UTC, DongGeon0908 requested changes
고생하셨습니다. 몇가지 디테일한 부분을 조금 더 수정하면 좋을 것 같아요

2022-09-14 12:45 UTC, DongGeon0908 commented on src/main/java/view/InitView.java
> +  int orderNumber;
접근 제한자는?

2022-09-14 12:45 UTC, DongGeon0908 commented on src/main/java/LottoSimulatorHandler/LottoSimulatorHandler.java
> +  OutView outView = new OutView();
접근제한자는?

2022-09-14 12:45 UTC, DongGeon0908 commented on src/main/java/LottoSimulatorHandler/LottoSimulatorHandler.java
> +  public void viewResolver() throws IOException {
IOException catch 안하고 던진 이유가 있을까요?

2022-09-14 12:45 UTC, DongGeon0908 commented on src/main/java/LottoSimulatorHandler/LottoSimulatorHandler.java
> +      rankPrint(lottoSimulatorController.getChallenger(), lottoSimulatorController.rank(lottoSimulatorController.getChallenger()));
조금 끊어주는 건 어떨까요??
읽기가 어려워요 ㅜㅜ

2022-09-14 12:45 UTC, DongGeon0908 commented on src/main/java/controller/LottoSimulatorController.java
> +public class LottoSimulatorController {
Controller를 Web으로 변경했을 때, 수정 없이 확장이 가능한 구조일까요?

2022-09-14 12:45 UTC, DongGeon0908 commented on src/main/java/model/CreateLottoNumbers.java
> +    List<Integer> answer = new ArrayList<>(createNumbers(Number.LOTTO_MAX_LENGTH, new Random()));
끊어주는건 어떨까요??

2022-09-14 12:45 UTC, DongGeon0908 commented on src/main/java/model/CreateNumbers.java
> +  default List<Integer> createNumbers(int length, Random random) {
interface에서 default 메서드를 사용하셨는데, 이유가 있을까요?

2022-09-14 12:45 UTC, DongGeon0908 commented on src/main/java/model/Lotto.java
> +}
각 번호를 저장하는 용도로 사용되는 객체일까요?

2022-09-14 12:45 UTC, DongGeon0908 commented on src/main/java/model/Number.java
> +  public static final int ZERO =0;
해당 상수들은 왜 따로 분리하신 걸까요?

2022-09-14 12:45 UTC, DongGeon0908 commented on src/main/java/model/User.java
> +}
User라는 네이밍을 가져가면, 정말 사용자라는 생각이 드는 것 같아요

2022-09-14 12:45 UTC, DongGeon0908 commented on src/main/java/repositroy/LottoSimulatorRepository.java
> +  List<Lotto> lottoNumbers = new ArrayList<>();
접근 제한자는?
메모리 구조로 가져가신건 매우 재밌네요!! 좋아요~

2022-09-14 12:45 UTC, DongGeon0908 commented on src/main/java/service/CheckLottoSimulatorService.java
> +  private int lottoCheckCount = Number.ZERO;
굳이 상수를 분리하지 않고, 여기서 상수를 선언해도 좋을 것 같네요

2022-09-14 12:45 UTC, DongGeon0908 commented on src/main/java/service/CheckLottoSimulatorService.java
> +    }
요건 좀 개선이 필욯갈 것 같아요

2022-09-21 14:00 UTC, DongGeon0908 reviewed
고생하셨습니다. 리뷰 확인 부탁드릴게요

2022-09-21 14:00 UTC, DongGeon0908 commented on src/test/java/view/OutViewTest.java
> +  void userNumberView() {
무엇을 위한 테스트인가요?
어떤것을 테스트하는 걸까요?

2022-09-21 14:00 UTC, DongGeon0908 commented on src/test/java/ModulTest.java
> +@Test
무엇을 위한 테스트일까요?

2022-09-21 14:00 UTC, DongGeon0908 commented on src/main/java/LottoSimulatorHandler/LottoSimulatorHandler.java
> +public class LottoSimulatorHandler {
handler는 어떤 역할을 하는 걸까요?
네이밍 전략이 궁금합니다.

2022-09-21 14:00 UTC, DongGeon0908 commented on src/main/java/LottoSimulatorMachine.java
> +    for(;;){
이런 for문은 지양해주세요

2022-09-21 14:00 UTC, DongGeon0908 commented on src/main/java/LottoSimulatorMachine.java
> +  }
try catch

2022-09-21 14:00 UTC, DongGeon0908 commented on src/main/java/controller/LottoSimulatorController.java
> +    for(int i= Number.ZERO; i<loopNumber;i++){
for문에서의 상수처리는 불필요합니다.

2022-09-21 14:00 UTC, DongGeon0908 commented on src/main/java/model/CreateNumbers.java
> +  }
너무 복잡한 것 같아요
그리고 interface라고 생각하기 어렵네요
차라리 class로 빼는게 어떨지

2022-09-21 14:00 UTC, DongGeon0908 commented on src/main/java/model/Number.java
> +}
명확한 의도가 있는 상수면 괜찮은데, 모든 필드값들을 여기서 처리할려고 하신 것 같네요
그리고 여기서 관리하기 보다는, 해당 상수를 쓰는 곳에서 관리해도 될듯 합니다.

2022-09-21 14:00 UTC, DongGeon0908 commented on src/main/java/service/CheckLottoSimulatorService.java
> +  }
코드를 더 분리할 수 있을 것 같은데요

2022-09-21 14:00 UTC, DongGeon0908 commented on src/main/java/service/CheckLottoSimulatorService.java
> +      lottoCheckCount++;
조건을 따로 빼는 건 어떨까요

2022-09-21 14:00 UTC, DongGeon0908 commented on src/main/java/view/InitView.java
> +  BufferedReader bf = new BufferedReader(new InputStreamReader(System.in));
여기는 왜 접근제한자가 없을까요

2022-09-21 14:00 UTC, DongGeon0908 commented on src/main/java/view/InitView.java
> +  public int startView() throws IOException {
throw 보다는 try catch로

2022-09-23 01:08 UTC, HwangHarim commented on src/test/java/view/OutViewTest.java
> +  void userNumberView() {
테스트를 구분 할 수 있도록 변경하겠습니다.

2022-09-23 02:15 UTC, HwangHarim commented on src/main/java/service/CheckLottoSimulatorService.java
> +      lottoCheckCount++;
조건을 따로 빼서 수정하겠습니다!

2022-09-23 02:27 UTC, HwangHarim commented on src/main/java/service/CheckLottoSimulatorService.java
> +  }
List에서 SET으로 변경해서 수정했습니다.

2022-09-24 02:19 UTC, HwangHarim commented on src/main/java/LottoSimulatorHandler/LottoSimulatorHandler.java
> +public class LottoSimulatorHandler {
handler의 역할은 view의 코드랑 Controller의 비즈니스 로직과 연결을 하기 위한 역할을 합니다.  ViewResolver의 역할을 생각하고 추가했습니다!

2022-09-24 03:39 UTC, HwangHarim commented on src/main/java/model/Number.java
> +}
상수를 쓰는 곳이 여러곳이 있어서 EX>controller에  Public static final로 했을 경우 service에서 상수를 쓰게 되면 controller.ONE 로 사용해야해서 상수는 따로 모아 놓는게 더 깔끔하다고 생각했습니다. 그러면 다양한 곳에서 상수를 사용하려고 하면 상수를 어디에 선언하고 사용해야 할 까요?

2022-09-25 10:34 UTC, DongGeon0908 reviewed
고생하셨습니다!!
해당 과제는 여기서 종료하면 될 것 같네요

2022-09-25 10:34 UTC, DongGeon0908 commented on src/test/java/model/CreateLottoNumbersTest.java
> +class CreateLottoNumbersTest {
테스트를 진행할때 예외 케이스에 대한 테스트를 진행하는게 중요해요!@

2022-09-25 10:34 UTC, DongGeon0908 commented on src/main/java/model/CreateNumbers.java
> +}
해당 기능을 인터페이스로 분리해서 사용하신 이유가 궁금하네요..
굳이 분리하지 않아도 될 것 같아서요

2022-09-25 10:34 UTC, DongGeon0908 commented
리뷰 한번만 확인해주세요!! merge하겠습니다.

2022-09-25 10:34 UTC, merged

2022-09-25 14:56 UTC, HwangHarim commented
바쁘신데 리뷰 감사합니다!