LottoSimulator 리뷰 요청 드립니다!! - 19 박창주
selab-hs/selab-lotto-simulator pull request #4
Opened 2023-07-13 11:36 UTC by ds4pae

2023-07-15 17:58 UTC, DongGeon0908 reviewed
배열 대신하여 List로 변경하여 작업 진행
객체지향 생활체조 원칙 지켜서 진행~

2023-07-15 17:58 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +            System.out.println(number + "  -> " + rank);
분리하는건?

2023-07-15 17:58 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +    private void printRandomNumbers(String[] randomNumbers, AutoNumber autoNumber) {
List 사용

2023-07-15 17:58 UTC, DongGeon0908 commented on src/main/java/RandomNumber.java
> +        System.out.println("********* 자동 생성 번호 *********");
분리하는건?

2023-07-18 08:06 UTC, ds4pae commented on src/main/java/RandomNumber.java
> +            System.out.println(number + "  -> " + rank);
`Output.printRandomNumbers(number, rank);`으로 변경했습니다.

2023-07-18 08:11 UTC, ds4pae commented on src/main/java/RandomNumber.java
> +    private void printRandomNumbers(String[] randomNumbers, AutoNumber autoNumber) {
`당첨 번호`와 `자동 생성 번호`를 List<String>으로 변경했습니다.

2023-07-18 08:23 UTC, ds4pae commented on src/main/java/RandomNumber.java
> +        System.out.println("********* 자동 생성 번호 *********");
`printRandomNumbers(randomNumbers, autoNumber);` 내에서
`Output.randomNumberScreen();`을 호출하는 것으로 변경했습니다.

2023-07-29 06:18 UTC, DongGeon0908 requested changes
배열 전부 컬렉션으로 변경하기

2023-08-04 12:41 UTC, DongGeon0908 requested changes
메서드가 하나의 일만 하도록 개선

코드 가독성이 떨어짐

2023-08-04 12:41 UTC, DongGeon0908 commented on src/main/java/Output.java
> +    private static int[] ranks = new int[6];
배열 부시기

2023-08-04 12:41 UTC, DongGeon0908 commented on src/main/java/Simulator.java
> +public class Simulator {
해당 클래스가 어떤 역할을 하는지 명확하게 모르겠어요

2023-08-04 12:41 UTC, DongGeon0908 commented on src/main/java/LottoSimulator.java
> +        }
```suggestion
        if(inputValue != 1) {
            Output.ExitScreen();
        }
```

Simulator simulator = new Simulator(); 별도로 실행
유효성 검사 로직과 같이 있을 이유가

2023-08-04 12:41 UTC, DongGeon0908 commented on src/main/java/AutoNumber.java
> +    final List<String> autoNumberResult = createAutoNumberResult(autoNumber);
이거는 어디서든 접근 가능한건가요?

2023-08-04 12:41 UTC, DongGeon0908 commented on src/main/java/CompareNumber.java
> +    }
메서드는 하나의 역할만 수행하도록, 구성해주세요

2023-08-04 12:41 UTC, DongGeon0908 commented on src/main/java/CompareNumber.java
> +    }
Enum 혹은 등수별 정보를 제공하는 객체가 있다면

2023-08-04 12:41 UTC, DongGeon0908 commented on src/main/java/CompareNumber.java
> +        String[] index2 = index1[0].split(" ");
배열 부시기

2023-08-09 12:40 UTC, ds4pae commented on src/main/java/CompareNumber.java
> +    }
기존 `checkRank()`는 값 변경 + 결과 출력이 동시에 있었는데,
`checkRank()`는 `hasBonus`와 `matchCount `값 변경으로만 사용하도록 바꾸었고,
`comparNumber()`에서 결과를 출력할 수 있도록 변경했습니다!!

2023-08-09 12:40 UTC, ds4pae commented on src/main/java/AutoNumber.java
> +    final List<String> autoNumberResult = createAutoNumberResult(autoNumber);
```java
private final List<Integer> autoNumber = createRandomNumbers();
private final List<String> autoNumberResult = createAutoNumberResult(autoNumber);

protected List<String> getAutoNumberResult() {
        return autoNumberResult;
    }
``` 
이런 방식으로 변경했습니다.
`String rank = CompareNumber.compareNumber(number, autoNumber.autoNumberResult);`
->이 부분에 문제가 있어
`String rank = CompareNumber.compareNumber(number, autoNumber.getAutoNumberResult());`
방식으로 사용했는데, getter를 사용하면 객체지향생활체조 원칙에 반하기 때문에 다른 방법을 고안해봐야겠네요...

2023-08-09 12:40 UTC, ds4pae commented on src/main/java/LottoSimulator.java
> +        }
```java
if(Input.getInputValue() != 1){
   Output.ExitScreen();
 }
RandomNumber randomNumber = new RandomNumber(Input.getSimulatorInput());
```
`ExitScreen()`안에 `System.exit(0);` 코드가 있어 검사 이후 실행되도록 변경했습니다!

2023-08-09 12:40 UTC, ds4pae commented on src/main/java/Simulator.java
> +public class Simulator {
굳이 따로 빼서 쓸 이유가 없었던 것 같네요.
`LottoSimulator` 클래스로 옮겨주었습니다!!

2023-08-22 15:51 UTC, DongGeon0908 requested changes
테스트코드를 통해 현재 로직들이 정상적으로 동작하는지 검증해주세요

2023-08-27 10:09 UTC, DongGeon0908 approved these changes

2023-08-27 10:10 UTC, merged